language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

services:
  - mysql

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

install:
  # Set default values for environment variables.
  - PROFILE=${PROFILE:="minimal"}
  - MODULES=${MODULES:="simpletest"}
  - TESTARGS=${TESTARGS:="--all"}

  # Set environment variables.
  - DIRPATH=$(pwd)
  - PHPINI="$HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini"
  - DRUPALDIR="$(dirname $DIRPATH)/drupal"
  - DRUPALHOST="127.0.0.1:1349"

  # Populate Composer packages.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install Drush.
  - composer global require --prefer-source --no-interaction drush/drush:8.*

  # Download Drupal.
  - drush dl drupal-7 --drupal-project-rename=$(basename $DRUPALDIR) --destination=$(dirname $DRUPALDIR)

   # Disable Sendmail.
  - echo sendmail_path=$(which true) >> $PHPINI
  # Increase the MySQL connection timeout on the PHP end.
  - echo "mysql.connect_timeout=3000" >> $PHPINI
  - echo "default_socket_timeout=3000" >> $PHPINI

  # Increase the MySQL server timetout and packet size.
  - mysql -uroot -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -uroot -e "SET GLOBAL max_allowed_packet = 33554432;"

  # Move module to Drupal.
  - mv $DIRPATH/ $DRUPALDIR/sites/all/modules/

before_script:
  - cd $DRUPALDIR
  # Install Drupal.
  - drush si -y $PROFILE --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name=Testsite
  # Enable set of modules.
  - drush en -y $MODULES
  # Start HTTP server.
  - drush runserver $DRUPALHOST > /dev/null 2>&1 &

script:
  - php scripts/run-tests.sh --verbose --color --concurrency 4 --php $(which php) --url http://$DRUPALHOST "$TESTARGS" | tee /tmp/test.txt
  # Exit with the inverted value, because if there are no fails found, it will exit with 1 and for us
  # that is a good thing so invert it to 0. Travis has some issues with the exclamation mark in front
  # so we have to fiddle a bit.
  # Also make the grep case insensitive and fail on run-tests.sh regular fails as well on fatal errors.
  - exit $(! egrep -i "([1-9]+ fail)|([1-9]+ exception)|(error)" /tmp/test.txt > /dev/null 2>&1) $?
